# Permalinks
permalink:        pretty

# Setup
title:            "L'Écriture Exemplaire"
tagline:          "Notes et réflexions autour des technologies numériques en Chine"
description:      "L'Écriture Exemplaire est un carnet de recherches regroupant notes, documents, et réflexions autour des technologies numériques en Chine.


Par [Clément Renaud](/about)."

#social
facebook_username:    LEcriture-Exemplaire-2326825127550213
github_username:      clemsos/ecriture.exemplaire.cc
telegram_username:    ecriture_exemplaire
twitter_username:     clemsos
rss:                  "true"


author:
  name:           Clément Renaud
  twitter:        clemsos
  url:            https://clementrenaud.com
  email:          bonjour@clementrenaud.com

paginate:         5
plugins: [jekyll-paginate]

markdown: kramdown

# Custom vars
github:           https://github.com/clemsos/ecriture.exemplaire.cc
