# Permalinks
permalink:        pretty

# Setup
title:            "L'Ecriture Exemplaire"
tagline:          ''
description:      ''


author:
  name:           Clément Renaud
  url:            https://twitter.com/clemsos
  email:          bonjour@clementrenaud.com

paginate:         5

markdown: kramdown

# Custom vars

github:
  repo:           https://github.com/clemsos/ecriture.exemplaire.cc
