# Permalinks
permalink:        pretty

# Setup
title:            "L'Ecriture Exemplaire"
tagline:          'Réflexions sur les technologies numériques en Chine'
description:      "L'Ecriture Exemplaire est un ensemble de notes, documents, et réflexions à propos des technologies numériques en Chine.


Par [Clément Renaud](/about)."

#social
facebook_username:    LEcriture-Exemplaire-2326825127550213
github_username:      clemsos/ecriture.exemplaire.cc
telegram_username:    ecriture_exemplaire
twitter_username:     clemsos
rss:                  "true"


author:
  name:           Clément Renaud
  twitter:        clemsos
  url:            https://clementrenaud.com
  email:          bonjour@clementrenaud.com

paginate:         5
plugins: [jekyll-paginate]

markdown: kramdown

# Custom vars
github:
  repo:           https://github.com/clemsos/ecriture.exemplaire.cc
