# Permalinks
permalink:        pretty

# Setup
title:            "L'Ecriture Exemplaire"
tagline:          ''
description:      "L'Ecriture Exemplaire est un ensemble de notes, documents, et réflexions par [Clément Renaud](/about) à propos des technologies numériques en Chine."

#social
facebook:         https://www.facebook.com/LEcriture-Exemplaire-2326825127550213


author:
  name:           Clément Renaud
  twitter:        clemsos
  url:            https://clementrenaud.com
  email:          bonjour@clementrenaud.com

paginate:         5

markdown: kramdown

# Custom vars

github:
  repo:           https://github.com/clemsos/ecriture.exemplaire.cc
